import type { Property } from '../types/property'

export const mockProperties: Property[] = [
  {
    id: '1',
    title: 'Boğaz Manzaralı Lüks Daire',
    slug: 'bogaz-manzarali-luks-daire',
    description:
      'Beşiktaş\'ın kalbinde, Boğaz manzaralı, tam eşyalı, güvenlikli sitede 3+1 lüks daire. Yüksek tavan, geniş balkon ve modern mutfak ile kusursuz bir yaşam sunuyor.',
    listingType: 'sale',
    propertyType: 'apartment',
    price: 12500000,
    currency: 'TRY',
    city: 'İstanbul',
    district: 'Beşiktaş',
    neighborhood: 'Sinanpaşa',
    location: { lat: 41.0438, lng: 29.0064 },
    rooms: '3+1',
    bathrooms: 2,
    grossArea: 185,
    netArea: 155,
    buildingAge: 3,
    floor: 8,
    totalFloors: 12,
    heating: 'Kombi',
    furnished: true,
    features: ['Balkon', 'Otopark', 'Güvenlik', 'Asansör', 'Havuz', 'Spor Salonu'],
    images: [
      {
        url: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800',
        path: 'properties/1/main.jpg',
        alt: 'Salon',
      },
    ],
    status: 'active',
    featured: true,
    viewCount: 342,
    ownerId: 'agent-1',
    createdAt: '2026-04-10T10:00:00Z',
    updatedAt: '2026-04-10T10:00:00Z',
  },
  {
    id: '2',
    title: 'Kadıköy Merkezde Kiralık Ofis Katı',
    slug: 'kadikoy-merkezde-kiralik-ofis-kati',
    description:
      'Kadıköy iş merkezinde, metro çıkışına 2 dakika mesafede, açık ofis planı ile 180 m² tam donanımlı ofis katı kiralık.',
    listingType: 'rent',
    propertyType: 'office',
    price: 85000,
    currency: 'TRY',
    city: 'İstanbul',
    district: 'Kadıköy',
    neighborhood: 'Moda',
    location: { lat: 40.9905, lng: 29.0233 },
    rooms: 'Açık Plan',
    bathrooms: 2,
    grossArea: 200,
    netArea: 180,
    buildingAge: 8,
    floor: 5,
    totalFloors: 10,
    heating: 'Merkezi',
    furnished: false,
    features: ['Asansör', 'Güvenlik', 'Otopark', 'Klima', 'Jeneratör'],
    images: [
      {
        url: 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=800',
        path: 'properties/2/main.jpg',
        alt: 'Ofis',
      },
    ],
    status: 'active',
    featured: false,
    viewCount: 198,
    ownerId: 'agent-2',
    createdAt: '2026-04-15T09:00:00Z',
    updatedAt: '2026-04-15T09:00:00Z',
  },
  {
    id: '3',
    title: 'Çeşme\'de Denize Sıfır Villa',
    slug: 'cesme-denize-sifir-villa',
    description:
      'Çeşme Alaçatı\'da, kendi özel plajına sahip, havuzlu, 5 odalı müstakil villa. Yaz ve kış yaşama uygun, tam izolasyonlu.',
    listingType: 'sale',
    propertyType: 'villa',
    price: 28000000,
    currency: 'TRY',
    city: 'İzmir',
    district: 'Çeşme',
    neighborhood: 'Alaçatı',
    location: { lat: 38.2829, lng: 26.3765 },
    rooms: '5+2',
    bathrooms: 4,
    grossArea: 450,
    netArea: 380,
    buildingAge: 2,
    floor: 0,
    totalFloors: 2,
    heating: 'Yerden Isıtma',
    furnished: true,
    features: ['Özel Havuz', 'Bahçe', 'Deniz Manzarası', 'Özel Plaj', 'Otopark', 'Güvenlik'],
    images: [
      {
        url: 'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800',
        path: 'properties/3/main.jpg',
        alt: 'Villa',
      },
    ],
    status: 'active',
    featured: true,
    viewCount: 521,
    ownerId: 'agent-1',
    createdAt: '2026-03-20T14:00:00Z',
    updatedAt: '2026-03-20T14:00:00Z',
  },
  {
    id: '4',
    title: 'Ankara Çankaya\'da 2+1 Kiralık Daire',
    slug: 'ankara-cankayada-2-1-kiralik-daire',
    description:
      'Çankaya\'nın sakin bir sokağında, ulaşımı kolay, ebeveyn banyolu, balkonlu 2+1 daire. Yeni boyalı, temiz.',
    listingType: 'rent',
    propertyType: 'apartment',
    price: 22000,
    currency: 'TRY',
    city: 'Ankara',
    district: 'Çankaya',
    neighborhood: 'Kavaklıdere',
    location: { lat: 39.9054, lng: 32.8597 },
    rooms: '2+1',
    bathrooms: 1,
    grossArea: 110,
    netArea: 95,
    buildingAge: 12,
    floor: 3,
    totalFloors: 6,
    heating: 'Doğalgaz (Kombi)',
    furnished: false,
    features: ['Balkon', 'Asansör', 'Ebeveyn Banyosu'],
    images: [
      {
        url: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800',
        path: 'properties/4/main.jpg',
        alt: 'Daire',
      },
    ],
    status: 'active',
    featured: false,
    viewCount: 87,
    ownerId: 'agent-3',
    createdAt: '2026-05-01T11:00:00Z',
    updatedAt: '2026-05-01T11:00:00Z',
  },
]
